//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_BackOffice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Encomenda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Encomenda()
        {
            this.Encomenda_Produto_Ingrediente = new HashSet<Encomenda_Produto_Ingrediente>();
        }
    
        public int ID { get; set; }
        public System.DateTime DataEncomenda { get; set; }
        public System.DateTime DataProcessamento { get; set; }
        public System.DateTime DataLevantamento { get; set; }
        public int Estado { get; set; }
        public string ClienteID { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Encomenda_Produto_Ingrediente> Encomenda_Produto_Ingrediente { get; set; }
    }
}
