//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_BackOffice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingrediente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ingrediente()
        {
            this.Encomenda_Produto_Ingrediente = new HashSet<Encomenda_Produto_Ingrediente>();
            this.ProdutoIngrediente = new HashSet<ProdutoIngrediente>();
        }
    
        public int ID { get; set; }
        public string Nome { get; set; }
        public decimal PrecoBase { get; set; }
        public string Imagem { get; set; }
        public bool Disponivel { get; set; }
        public bool Quente { get; set; }
        public bool Frio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Encomenda_Produto_Ingrediente> Encomenda_Produto_Ingrediente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdutoIngrediente> ProdutoIngrediente { get; set; }
    }
}
