//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_BO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Encomenda_Produto_Ingrediente
    {
        public int EncomendaID { get; set; }
        public int ProdutoID { get; set; }
        public int IngredienteID { get; set; }
        public int Quantidade { get; set; }
        public int PrecoBase { get; set; }
    
        public virtual Encomenda Encomenda { get; set; }
        public virtual Ingrediente Ingrediente { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
